src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Hourly_Rate__c</fullName>
        <label>Hourly-Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_User_Assignment__c.object
<CustomObject>
    <description>this hold the user workin on the project</description>
    <fields>
        <fullName>Hourly_Rate__c</fullName>
        <label>Hourly Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Is_Deactivated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deactivated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Project_Manager__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Project Manager</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project User Assignments</relationshipLabel>
        <relationshipName>Project_User_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_User_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project User Assignment</label>
    <nameField>
        <displayFormat>UA-{00000}</displayFormat>
        <label>Project User Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project User Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProjectAssignmentsSelector.cls
public with sharing class ProjectAssignmentsSelector extends SObjectSelector {
    
    public override List<Schema.SObjectField> getSObjectFieldList()
    {
        return new List<Schema.SObjectField> {
            Project_User_Assignment__c.Id,
            Project_User_Assignment__c.User__c,
            Project_User_Assignment__c.Project__c,
            Project_User_Assignment__c.Hourly_rate__c,
            Project_User_Assignment__c.Is_Deactivated__c,
            Project_User_Assignment__c.Is_Project_Manager__c
        };
    }
    
    public override Schema.SObjectType getSObjectType()
    {
        return Project_User_Assignment__c.sObjectType;
    }

    public List<Project_User_Assignment__c> selectById(Set<Id> idSet)
    {
    	 String query = String.format(
            'select {0},Project__r.Name,Project__r.OwnerId from {1} ' + 
            'where Id in :idSet ' , 
            new List<String>{ getFieldListString(), getSObjectName()});
    
        return (List<Project_User_Assignment__c>) Database.query(query);
        //return (List<Project_User_Assignment__c>) selectSObjectsById(idSet);
    }
    
    public List<Project_User_Assignment__c> selectByProject(Set<ID> idSet)
    {
        String query = String.format(
            'select {0},Project__r.Name,Project__r.Hourly_Rate__c from {1} ' + 
            'where Project__c in :idSet ' +
            'order by SystemModstamp DESC', 
            new List<String>{ getFieldListString(), getSObjectName()});
    
        return (List<Project_User_Assignment__c>) Database.query(query);
    
    }
    
    public List<Project_User_Assignment__c> selectAssignmentByProjectByUser(Set<ID> projectIdSet,Set<ID> userIdSet){
    	
    	String query = String.format(
            'select {0},Project__r.Name,Project__r.Hourly_Rate__c from {1} ' + 
            'where User__c in :userIdSet AND Project__c in :projectIdSet ' +
            'order by SystemModstamp DESC', 
            new List<String>{ getFieldListString(), getSObjectName()});
    
        return (List<Project_User_Assignment__c>) Database.query(query);
    }
    
    public List<Project_User_Assignment__c> projectsAssignedToUser(Set<ID> idSet)
    {
        String query = String.format(
            'select {0},Project__r.Name,Project__r.Hourly_Rate__c from {1} ' + 
            'where User__c in :idSet ' +
            'order by SystemModstamp DESC', 
            new List<String>{ getFieldListString(), getSObjectName()});
    
        return (List<Project_User_Assignment__c>) Database.query(query);
    
    }
    
    
}