src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_User_Assignment__c.object
<CustomObject>
    <description>this hold the user workin on the project</description>
    <fields>
        <fullName>Is_Deactivated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deactivated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Project_Manager__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Project Manager</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project User Assignments</relationshipLabel>
        <relationshipName>Project_User_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_User_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project User Assignment</label>
    <nameField>
        <displayFormat>UA-{00000}</displayFormat>
        <label>Project User Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project User Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Timesheet__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approval Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Timesheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Timesheets</relationshipLabel>
        <relationshipName>Timesheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UserTimesheet</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Time Sheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AutoCreateTimesheetWeeklyBatch.cls
/*
	@author : Sneha
	@date : 10/1/2017
	@purpose: Batch class to create weekly timesheet for all the team memebers of the projects
*/
public with sharing class AutoCreateTimesheetWeeklyBatch implements Database.Batchable<sObject>{

   public AutoCreateTimesheetWeeklyBatch(){
   		
   }
	
   /*
   	@purpose : this method quesry the data that will be used in the process
   */
   public Database.QueryLocator start(Database.BatchableContext BC){
      String query = 'Select User__c,Project__c,Is_Project_Manager__c,Project__r.OwnerId FROM Project_User_Assignment__c WHERE Is_Deactivated__c=false';
      return Database.getQueryLocator(query);
   }

	/*
		@description : this method process the record set and creates timesheet for each of the 
		active user in a project
   */
   public void execute(Database.BatchableContext BC, List<Project_User_Assignment__c> scope){
    	
    	List<Timesheet__c> timesheets = new List<Timesheet__c>();
    	for(Project_User_Assignment__c record :scope){
    		 Timesheet__c timeSheet = new Timesheet__c(Project__c=record.Project__c,User__c=record.User__c);
	         timeSheet.Start_Date__c = Date.today().addDays(1).toStartOfWeek();
	         timeSheet.End_Date__c = timeSheet.Start_Date__c.toStartOfWeek().addDays(7);
	         timeSheet.Approval_Manager__c =  record.Project__r.OwnerId;
	         timesheets.add(timeSheet);
    	}
    	
    	insert timesheets;   	
   }

   public void finish(Database.BatchableContext BC){
   }
	
    
}