src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_User_Assignment__c.object
<CustomObject>
    <description>this hold the user workin on the project</description>
    <fields>
        <fullName>Is_Project_Manager__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Project Manager</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project User Assignments</relationshipLabel>
        <relationshipName>Project_User_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_User_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project User Assignment</label>
    <nameField>
        <displayFormat>UA-{00000}</displayFormat>
        <label>Project User Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project User Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Task_Assignment__c.object
<CustomObject>
    <description>Manage Assignment of Tasks with Projects</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Harvest_Task_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipName>Harvest_Task_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Task Assignment</label>
    <nameField>
        <displayFormat>TA-{000000}</displayFormat>
        <label>Task Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>Task_Assignment__r.Project__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stopped</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Task_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>links the time entry to a project &amp; Task</description>
        <label>Task Assignment</label>
        <referenceTo>Task_Assignment__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <formula>Task_Assignment__r.Task__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Task</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timer_Started_At__c</fullName>
        <label>Timer Started At</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Timesheet__c</fullName>
        <label>Timesheet</label>
        <referenceTo>Timesheet__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Timesheet__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approval Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Timesheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Timesheets</relationshipLabel>
        <relationshipName>Timesheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>controlled via approval process</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recalled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UserTimesheet</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Time Sheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TimeTrackerComponentController.cls
/**
* @author Sneha
* @date 7/01/2017
* @description Controller class that communicates with ligntning component
*/
public with sharing class TimeTrackerComponentController{
    
    /**
    * @author Sneha
    * @date 8/01/2017
    * @description It returns all the task that are available for user on a project he is on currently
    */
    
    @AuraEnabled
    public static List<Task_Assignment__c> getTaskForProject(String searchKeyWord) {
        String searchKey = searchKeyWord + '%';
        List<Task_Assignment__c> availableTasks = 
                [SELECT Id, Task__c, Project__c, Task__r.description__c,Task__r.Name  FROM Task_Assignment__c WHERE  Task__r.Name LIKE: searchKey AND Project__c IN (Select Project__c FROM Project_User_Assignment__c WHERE User__c =:UserInfo.getUserId())];
		system.debug(availableTasks);
        return availableTasks;
    }
    
   
    
    /**
    * @author Sneha
    * @date 8/01/2017
    * @description this will return list of time entry that has been created today 
    */
    @AuraEnabled
    public static List<Time_Entry__c> getTodayTimerEntry() {
        List<Time_Entry__c> currentTimeEntry = 
             [SELECT Id, Task__c,Project__c, Timer_Started_At__c,Status__c FROM Time_Entry__c WHERE Date__c = TODAY AND  User__c =:UserInfo.getUserId()];
        return currentTimeEntry;
    }
    
    /**
    * @author Sneha
    * @date 8/01/2017
    * @description this method will start a new timer record  called from lightning component
    */
    @AuraEnabled
    public static void startTimer(Task_Assignment__c selectedTask) {
     	 
     	 //first fetch the time sheet record for this week if not found create one:-
     	 List<Timesheet__c> thisWeekTimesheetList = [Select Id FROM Timesheet__c WHERE Start_Date__c = THIS_WEEK AND User__c=:UserInfo.getUserId()];
     	 Timesheet__c thisWeekTimesheet;
     	 if(thisWeekTimesheetList.size()==0){
     	 	//create one for this week
     	 	thisWeekTimesheet=createTimesheet(selectedTask.project__c);	
     	 }else{
     	 	thisWeekTimesheet = thisWeekTimesheetList[0];
     	 }
     	      	 
     	 Time_Entry__c newEntry = new Time_Entry__c();
     	 newEntry.Task_Assignment__c =selectedTask.Id;
     	 newEntry.Date__c = Date.today();
     	 newEntry.Timer_Started_At__c = DateTime.Now();
     	 newEntry.timesheet__c = thisWeekTimesheet.Id;
     	 newEntry.Status__c = 'Started';
     	 newEntry.User__c=UserInfo.getUserId();
     	 insert newEntry;
    }
    
    /**
    * @author Sneha
    * @date 8/01/2017
    * @description method to stop the timer record called from lightning component
    */
    @AuraEnabled
    public static void stopTimerRecord(Time_Entry__c timeEntry) {
     	
     	timeEntry.status__c='Stopped';
     	update  timeEntry;
     	 
    }
    
     /**
    * @author Sneha
    * @date 8/01/2017
    * @description method to stop the timer record called from lightning component
    */
    @AuraEnabled
    public static void resumeTimerRecord(Time_Entry__c timeEntry) {
     	
     	timeEntry.status__c='Started';
     	update  timeEntry;
     	 
    }
    
   
    /**
    * @author Sneha
    * @date 9/01/2017
    * @description : helper method that will create a timesheet if not found
    * @params : id of the project for which we are creating the timesheet
    */
     public static Timesheet__c createTimesheet(String projectId) {
     	 
     	 List<Project_User_Assignment__c> manager = [Select User__c FROM Project_User_Assignment__c WHERE Project__c=:projectId AND Is_Project_Manager__c=true];
     	 
     	 Timesheet__c timeSheet = new Timesheet__c(Project__c=projectId,User__c=UserInfo.getUserId());
     	 timeSheet.Start_Date__c = Date.today().toStartOfWeek();
     	 timeSheet.End_Date__c = Date.today().toStartOfWeek().addDays(7);
     	 if(manager.size()>0)
     	 	timeSheet.Approval_Manager__c =  manager[0].User__c;
     	 	
     	 insert timeSheet;
     	 return timeSheet;
     }
    
}