src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Bill_by__c</fullName>
        <label>Bill by</label>
        <picklist>
            <picklistValues>
                <fullName>People</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tasks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Hourly_Rate__c</fullName>
        <label>Hourly-Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_User_Assignment__c.object
<CustomObject>
    <description>this hold the user workin on the project</description>
    <fields>
        <fullName>Hourly_Rate__c</fullName>
        <label>Hourly Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project User Assignments</relationshipLabel>
        <relationshipName>Project_User_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_User_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project User Assignment</label>
    <nameField>
        <displayFormat>UA-{00000}</displayFormat>
        <label>Project User Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project User Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Task_Assignment__c.object
<CustomObject>
    <description>Manage Assignment of Tasks with Projects</description>
    <fields>
        <fullName>Hourly_rate__c</fullName>
        <label>Hourly rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Harvest_Task_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Task Assignment</label>
    <nameField>
        <displayFormat>TA-{000000}</displayFormat>
        <label>Task Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Bill_By_Rate__c</fullName>
        <label>Bill By Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>Task_Assignment__r.Project__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stopped</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Task_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>links the time entry to a project &amp; Task</description>
        <label>Task Assignment</label>
        <referenceTo>Task_Assignment__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Timer_Log__c.object
<CustomObject>
    <description>this object is used to keep track of the start &amp; stop time of the tracker</description>
    <fields>
        <fullName>Time_Entry__c</fullName>
        <label>Time Entry</label>
        <referenceTo>Time_Entry__c</referenceTo>
        <relationshipLabel>Timer Log</relationshipLabel>
        <relationshipName>Timer_Log</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Timer Log</label>
    <nameField>
        <displayFormat>TL-{0000000}</displayFormat>
        <label>Timer Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timer Log</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TimeEntries.cls
/*
    Domain class for time entry it handles all the specific function 
    related to time entry
*/
public with sharing class TimeEntries extends SObjectDomain
{
	  /**
	* @author Sneha
	* @date 12/1/2017
	* @description Initialize the parent
	* @return none
	*/
    public TimeEntries(List<Time_Entry__c> sObjectList)
    {
        // Domain classes are initialised with lists to enforce bulkification throughout
        super(sObjectList);
    }
    
   /**
	* @author Sneha
	* @date 12/1/2017
	* @description This overrides the method of base class : Method creates the Timer record for the newly inserted
	  time entry
	* @return none
	*/
    public override void onAfterInsert()
    {
        /*
            handle the action that we need to perform when trigger is fire after insert record
        */      
        //create the time tracker records for this we delegate the work the TimerService
        //delegate to the time log domain
        new TimerLogs(new List<Timer_Log__c>()).createTimer(new Map<Id,Time_Entry__c>((List<Time_Entry__c>) Records).keySet());              
    } 
   
   
   /**
	* @author Sneha
	* @date 12/1/2017
	* @description This overrides the method of base class : Method creates/updates the Timer record for the updated
	  time entry
	* @return none
	*/
    
    public override void onAfterUpdate(Map<Id,SObject> existingRecords)
    {    
    	//hold the record id for whic new timer record needs to be inserted           
        Set<Id> timeEntryId = new Set<Id>();
        
        //hold the record whose timer need to be stopped
        Set<Id> timeEntryIdToStop = new Set<Id>();     
        for(Time_Entry__c entry :(List<Time_Entry__c>) Records){
            if(entry.status__c ==TimeTrackerConstants.TIMER_STARTED && ((Time_Entry__c)existingRecords.get(entry.Id)).Status__c!=entry.status__c){
                timeEntryId.add(entry.Id);
            }
            if(entry.status__c ==TimeTrackerConstants.TIMER_STOPPED ){
                timeEntryIdToStop.add(entry.Id);
            }
        }

        //delegate this action to Time Log Domain class
        SObjectUnitOfWork uow = new SObjectUnitOfWork(new Schema.SObjectType[] { Timer_Log__c.SObjectType });  
        
        if(timeEntryId.size()>0)new TimerLogs(new List<Timer_Log__c>()).createTimer(timeEntryId,uow);
        if(timeEntryIdToStop.size()>0)new TimerLogs(new TimerLogsSelector().selectTimerNotClosed(timeEntryIdToStop)).updateEndDate(uow); 
        uow.commitWork(); 
    }
    
    /**
	* @author Sneha
	* @date 12/1/2017
	* @description This overrides the method of base class : This performs the action to populate the rate of task 
	  based on bill by field on project. This value is used for amount calculation
	* @return none
	*/
    public override void onBeforeInsert()
    {
        Set<Id> taskAssignmentId = new Set<Id> ();
        Set<Id> projectId = new Set<Id> ();
        
        //get the task assignment id to fetch the details of project rate,tasks rates
        for(Time_Entry__c entry :(List<Time_Entry__c>) Records){
            taskAssignmentId.add(entry.Task_Assignment__c); 
        }
        
        //get all the required details
        Map<Id,Task_Assignment__c> taskRecord = new Map<Id,Task_Assignment__c>(
                                                new TaskAssignmentsSelector().selectById(taskAssignmentId)
                                                );
        
        //init the project id as we need to get user rate from project team
        for(Task_Assignment__c record : taskRecord.values()){
            projectId.add(record.project__c);
        }
        
        //get the data
        List<Project_User_Assignment__c> userRates = new ProjectAssignmentsSelector ().selectByProject(projectId);
        
        //init the map with user/project rate                                             
        Map<String,Double> userRateMap = new Map<String,Double>();
        for(Project_User_Assignment__c assignment:userRates)
                userRateMap.put(assignment.project__c+'-'+assignment.user__c,assignment.Hourly_Rate__c);
        
        //finally update the rate in the record     
        for(Time_Entry__c entry :(List<Time_Entry__c>) Records){
            Double rate = taskRecord.get(entry.Task_Assignment__c).Project__r.Bill_by__c=='Project' ?
                          taskRecord.get(entry.Task_Assignment__c).Project__r.Hourly_Rate__c:
                          taskRecord.get(entry.Task_Assignment__c).Project__r.Bill_by__c=='Task' ?
                          taskRecord.get(entry.Task_Assignment__c).Hourly_Rate__c :
                          userRateMap.get(taskRecord.get(entry.Task_Assignment__c).Project__c+'-'+entry.user__c);
                        
            entry.Bill_By_Rate__c = rate;
        }   
        
    }
    
    public class Constructor implements SObjectDomain.IConstructable
    {
        public SObjectDomain construct(List<SObject> sObjectList)
        {
            return new TimeEntries(sObjectList);
        }
    }
}