src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_User_Assignment__c.object
<CustomObject>
    <description>this hold the user workin on the project</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project User Assignments</relationshipLabel>
        <relationshipName>Project_User_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_User_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project User Assignment</label>
    <nameField>
        <displayFormat>UA-{00000}</displayFormat>
        <label>Project User Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project User Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Timesheet__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approval Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Timesheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Timesheets</relationshipLabel>
        <relationshipName>Timesheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UserTimesheet</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Time Sheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TimesheetsService.cls
/*
    Service Layer for Timeshet

*/
public with sharing class TimesheetsService {
    
    /*
    	
    */ 
    public static List<Timesheet__c> createThisWeekTimesheet(Set<Id> projectAssignmentId){ 
    	
    	 List<Project_User_Assignment__c> projectUsers = new ProjectAssignmentsSelector().selectById(projectAssignmentId);
    	 
    	 SObjectUnitOfWork uow = new SObjectUnitOfWork(new Schema.SObjectType[] { TimeSheet__c.SObjectType });  
    	 
    	 List<Timesheet__c> newTimesheets = new List<Timesheet__c>();
    	 for(Project_User_Assignment__c projUser : projectUsers) {
    	 	Timesheet__c timeSheet = new Timesheet__c(Project__c=projUser.Project__c,User__c=projUser.User__c);	
    	 	timeSheet.Start_Date__c = Date.today().toStartOfWeek();
    	 	timeSheet.End_Date__c = Date.today().toStartOfWeek().addDays(6);
    	 	timeSheet.Approval_Manager__c =  projUser.Project__r.OwnerId; 
    	 	
    	 	uow.registerNew(timeSheet);
    	 	newTimesheets.add(timeSheet);
    	 }
     	 uow.commitWork();  
     	 
     	 return newTimesheets;
    }
    
    
}