src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Timesheet__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approval Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Timesheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Timesheets</relationshipLabel>
        <relationshipName>Timesheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>controlled via approval process</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recalled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UserTimesheet</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Time Sheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TimesheetsSelector.cls
public with sharing class TimesheetsSelector extends SObjectSelector {
    
    public override List<Schema.SObjectField> getSObjectFieldList()
    {
        return new List<Schema.SObjectField> {
            Timesheet__c.Id,
            Timesheet__c.User__c,
            Timesheet__c.Project__c,
            Timesheet__c.Start_Date__c,
            Timesheet__c.Approval_Manager__c,
            Timesheet__c.Status__c
        };
    }
    
    public override Schema.SObjectType getSObjectType()
    {
        return Timesheet__c.sObjectType;
    }
    
    public List<Timesheet__c> getCurrentWeekTimesheetForUser(Set<ID> idSet)
    {
        String query = String.format(
            'select {0} from {1} ' + 
            'where User__c in :idSet AND Start_Date__c = THIS_WEEK' +
            ' order by SystemModstamp DESC', 
            new List<String>{ getFieldListString(), getSObjectName()});
    	system.debug(query);
        return (List<Timesheet__c>) Database.query(query);
    
    } 
}