src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Bill_by__c</fullName>
        <label>Bill by</label>
        <picklist>
            <picklistValues>
                <fullName>People</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tasks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Hourly_Rate__c</fullName>
        <label>Hourly-Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Task_Assignment__c.object
<CustomObject>
    <description>Manage Assignment of Tasks with Projects</description>
    <fields>
        <fullName>Deactivated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deactivated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hourly_rate__c</fullName>
        <label>Hourly rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Harvest_Task_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipName>Harvest_Task_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Task Assignment</label>
    <nameField>
        <displayFormat>TA-{000000}</displayFormat>
        <label>Task Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TaskAssignmentsSelector.cls
public with sharing class TaskAssignmentsSelector extends SObjectSelector{
    
    public override List<Schema.SObjectField> getSObjectFieldList()
    {
        return new List<Schema.SObjectField> {
            Task_Assignment__c.Id,
            Task_Assignment__c.Task__c,
            Task_Assignment__c.Project__c,
            Task_Assignment__c.Hourly_rate__c,
            Task_Assignment__c.Deactivated__c
        };
    }
    
    public override Schema.SObjectType getSObjectType()
    {
        return Task_Assignment__c.sObjectType;
    }

    public List<Task_Assignment__c> selectById(Set<ID> idSet)
    {
        List<String> selectFields = 
        new List<String> {  
            'Id', 
            'Task__c', 
            'Project__c', 
            'Project__r.Name', 
            'Task__r.Name', 
            'Task__r.Description__c',
            'Project__r.Hourly_Rate__c',
            'Hourly_rate__c',
            'Project__r.Bill_by__c'
        };
        
        String query  = String.format('select {0} from {1} where Id in :idSet', 
                        new List<String> { String.join(selectFields, ','), getSObjectName() }
                        );
        
        return (List<Task_Assignment__c>) Database.query(query);    
    }
    
    public List<Task_Assignment__c> searchByTaskProjectId(String taskKeyword,Set<ID> idSet)
    {
        List<String> selectFields = 
        new List<String> {  
            'Id', 
            'Task__c', 
            'Project__c', 
            'Project__r.Name', 
            'Task__r.Name', 
            'Task__r.Description__c' };
        String searchKey = taskKeyword+'%';
        String query  = String.format('select {0} from {1} where Project__c in :idSet AND Task__r.Name LIKE :searchKey', 
                        new List<String> { String.join(selectFields, ','), getSObjectName() }
                        );
        
        return (List<Task_Assignment__c>) Database.query(query);    
    }
         
}