src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Bill_by__c</fullName>
        <label>Bill by</label>
        <picklist>
            <picklistValues>
                <fullName>People</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tasks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Hourly_Rate__c</fullName>
        <label>Hourly-Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_User_Assignment__c.object
<CustomObject>
    <description>this hold the user workin on the project</description>
    <fields>
        <fullName>Hourly_Rate__c</fullName>
        <label>Hourly Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project User Assignments</relationshipLabel>
        <relationshipName>Project_User_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_User_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project User Assignment</label>
    <nameField>
        <displayFormat>UA-{00000}</displayFormat>
        <label>Project User Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project User Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Task_Assignment__c.object
<CustomObject>
    <description>Manage Assignment of Tasks with Projects</description>
    <fields>
        <fullName>Hourly_rate__c</fullName>
        <label>Hourly rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Harvest_Task_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Task Assignment</label>
    <nameField>
        <displayFormat>TA-{000000}</displayFormat>
        <label>Task Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Bill_By_Rate__c</fullName>
        <label>Bill By Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>Task_Assignment__r.Project__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stopped</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Task_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>links the time entry to a project &amp; Task</description>
        <label>Task Assignment</label>
        <referenceTo>Task_Assignment__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Timer_Log__c.object
<CustomObject>
    <description>this object is used to keep track of the start &amp; stop time of the tracker</description>
    <fields>
        <fullName>Ended_At__c</fullName>
        <label>Ended At</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Started_At__c</fullName>
        <label>Started At</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Time_Entry__c</fullName>
        <label>Time Entry</label>
        <referenceTo>Time_Entry__c</referenceTo>
        <relationshipLabel>Timer Log</relationshipLabel>
        <relationshipName>Timer_Log</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Timer Log</label>
    <nameField>
        <displayFormat>TL-{0000000}</displayFormat>
        <label>Timer Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timer Log</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TimeTrackerTriggerHelper.cls
/**
	@author : Sneha
	@date : 10/1/2017
	@purpose : Class contains all the methods that are invoked in trigger execution
 */
public class TimeTrackerTriggerHelper{

    /*
    	@author : Sneha
		@date : 10/1/2017
		@purpose : this method is fired when the new time entry record is create. This method then populate the amount 
		value based on the project billy parameter
		
		@params : list of Time_Entry__c
    */
    public static void updateRates(List<Time_Entry__c> records){
    	
    	List<String> taskAssignmentId = new List<String> ();
    	List<String> projectId = new List<String> ();
    	
    	//get the task assignment id to fetch the details of project rate,tasks rates
    	for(Time_Entry__c entry :records){
    		taskAssignmentId.add(entry.Task_Assignment__c);	
    	}
    	
    	//get all the required details
    	Map<Id,Task_Assignment__c> taskRecord = new Map<Id,Task_Assignment__c>(
										    	[Select Id,Project__c,Project__r.Hourly_Rate__c,
										    	        Project__r.Bill_by__c ,Hourly_rate__c
										    	 FROM Task_Assignment__c 
										    	 WHERE Id IN:taskAssignmentId ]
										    	);
    	
    	//init the project id as we need to get user rate from project team
    	for(Task_Assignment__c record : taskRecord.values()){
    		projectId.add(record.project__c);
    	}
    	
    	//get the data
    	List<Project_User_Assignment__c> userRates = [Select Id,Hourly_Rate__c,User__c,Project__c 
    												  FROM Project_User_Assignment__c 
    												  WHERE Project__c IN:projectId];
    	
    	//init the map with user/project rate											  
    	Map<String,Double> userRateMap = new Map<String,Double>();
    	for(Project_User_Assignment__c assignment:userRates)
    			userRateMap.put(assignment.project__c+'-'+assignment.user__c,assignment.Hourly_Rate__c);
    	
    	//finally update the rate in the record		
    	for(Time_Entry__c rec : records){
    		Double rate = taskRecord.get(rec.Task_Assignment__c).Project__r.Bill_by__c=='Project' ?
    					  taskRecord.get(rec.Task_Assignment__c).Project__r.Hourly_Rate__c:
    					  taskRecord.get(rec.Task_Assignment__c).Project__r.Bill_by__c=='Task' ?
    					  taskRecord.get(rec.Task_Assignment__c).Hourly_Rate__c :
    					  userRateMap.get(taskRecord.get(rec.Task_Assignment__c).Project__c+'-'+rec.user__c);
    					
    		rec.Bill_By_Rate__c = rate;
    	}			
    	
    }
    
    /*
    	@author : Sneha
		@date : 10/1/2017
		@purpose : this method is fired when the new time entry record is created. It create a  timer record which keeps 
		track of start and end time. This will create with record start time
		
		@params : list of Time_Entry__c
    */
    
    public static void insertTimer(List<Time_Entry__c> records){
        
         
           List<Timer_Log__c> logs = new List<Timer_Log__c>();              
           for(Time_Entry__c entry  : records){
                if(entry.status__c=='Started'){
                   logs.add(new Timer_Log__c(Started_At__c=Datetime.now(),Time_Entry__c=entry.id)); 
                }   
           }
           
           insert logs;
    }
    
    /*
    	@author : Sneha
		@date : 10/1/2017
		@purpose : this method is fired when the  time entry record is being created. IIt stops the previous entry
		
		@params : none
    */
    public static void stopOtherTimerEntry(){
    	List<Time_Entry__c> userExistingRecord =[Select Id,Status__c FROM Time_Entry__c
    											 WHERE Status__c='Started' AND User__c =:UserInfo.getUserId()
    											];
    	
    	for(Time_Entry__c entry : userExistingRecord){
    		entry.status__c='Stopped';	
    	}
    	
    	update userExistingRecord;
    		
    }
    
    /*
    	@author : Sneha
		@date : 10/1/2017
		@purpose : this method is fired when the  time entry record is updated. It updates a  timer record which keeps 
		track of start and end time. This will update the record end time
		
		@params : list of Time_Entry__c
    */
    public static void stopTimer(List<Time_Entry__c> records){
           
           //get the all the time log records where end date not presetm
           Map<Id, Time_Entry__c > entryIdMap = new Map<Id, Time_Entry__c>(records);
             
           List<Timer_Log__c> logs = [Select Id,Ended_At__c FROM Timer_Log__c WHERE Ended_At__c=null AND Time_Entry__c IN : entryIdMap.keySet() AND Time_Entry__r.Status__c='Stopped'];             
           for(Timer_Log__c entry  : logs ){
                entry.Ended_At__c = DateTime.Now();
           }
           
           update logs;
    }


}