src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Task_Assignment__c.object
<CustomObject>
    <description>Manage Assignment of Tasks with Projects</description>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Harvest_Task_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Task Assignment</label>
    <nameField>
        <displayFormat>TA-{000000}</displayFormat>
        <label>Task Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Bill_By_Rate__c</fullName>
        <label>Bill By Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>Task_Assignment__r.Project__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stopped</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Task_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>links the time entry to a project &amp; Task</description>
        <label>Task Assignment</label>
        <referenceTo>Task_Assignment__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestTimeTrackerComponentController.cls
/**
	@author:SNeha
	@date : 10/1/2017
	@purpose : this class contains the unit testmethod for the time tracker controller & helper
 */
@isTest
private class TestTimeTrackerComponentController {

    static testMethod void testTodayTimerEntry() {
        //setup the data
        Project__c project = TestDataHelper.setupProject();
        
        List<Task_Assignment__c> tasks = TestDataHelper.createTaskUnderProject(project.Id);
        
        Test.startTest();
        	system.assert(TimeTrackerComponentController.getTodayTimerEntry().size()==0);
        	
        	//now create timer:-
        	TimeTrackerComponentController.startTimer(tasks[0]);
        	system.assert(TimeTrackerComponentController.getTodayTimerEntry().size()>0);
        Test.stopTest();
        
    }
    
    static testMethod void testGetTaskListOfProject() {
        //setup the data
        Project__c project = TestDataHelper.setupProject();
        
        List<Task_Assignment__c> tasks = TestDataHelper.createTaskUnderProject(project.Id);
        
        Test.startTest();
        	system.assert(TimeTrackerComponentController.getTaskForProject('Sa').size()==tasks.size());
        Test.stopTest();
        
    }
    
    static testMethod void testTimerFunctions() {
        //setup the data
        Project__c project = TestDataHelper.setupProject();
        
        List<Task_Assignment__c> tasks = TestDataHelper.createTaskUnderProject(project.Id);
        
        Test.startTest();
        	system.assert(TimeTrackerComponentController.getTodayTimerEntry().size()==0);
        	
        	//now create timer:-
        	TimeTrackerComponentController.startTimer(tasks[0]);
        	List<Time_Entry__c> entries = TimeTrackerComponentController.getTodayTimerEntry();
        	system.assert(entries.size()>0);
        	
        	//now stop the time:-
        	TimeTrackerComponentController.stopTimerRecord(entries[0]);
        	//check the entry record status
        	
        	Time_Entry__c t = [Select Id,Status__c,Bill_By_Rate__c FROM Time_Entry__c WHERE Id=:entries[0].Id];
        	system.assert(t.Status__c=='Stopped');
        	
        	system.assert(t.Bill_By_Rate__c==50);
        	
        	TimeTrackerComponentController.resumeTimerRecord(entries[0]);
        	t = [Select Id,Status__c FROM Time_Entry__c WHERE Id=:entries[0].Id];
        	system.assert(t.Status__c=='Started');
        Test.stopTest(); 
        
    }
    
    
    
}