src/objects/Task_Assignment__c.object
<CustomObject>
    <description>Manage Assignment of Tasks with Projects</description>
    <label>Task Assignment</label>
    <nameField>
        <displayFormat>TA-{000000}</displayFormat>
        <label>Task Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stopped</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Task_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>links the time entry to a project &amp; Task</description>
        <label>Task Assignment</label>
        <referenceTo>Task_Assignment__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Timer_Started_At__c</fullName>
        <label>Timer Started At</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Timesheet__c</fullName>
        <label>Timesheet</label>
        <referenceTo>Timesheet__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Timesheet__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>controlled via approval process</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recalled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UserTimesheet</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Time Sheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TimeEntriesService.cls
public with sharing class TimeEntriesService {
    
    /**
	* @author Sneha
	* @date 12/1/2017
	* @description method creates TimeEntry record under project for given timesheet
 	* @param taskAssignmentId  id of the Task & Project for which we are creating this entry
 	* @params timesheetId id of the timesheet record under which this record is created
 	* @param  userId : id of the user for whom this record is created
	* @return none
	*/
     public static void createTimeEntryForProjectTask(Set<Id> taskAssignmentId, String timesheetId,String userId)
    {
        // Create unit of work to capture work and commit it under one transaction
        SObjectUnitOfWork uow = new SObjectUnitOfWork(SERVICE_SOBJECTS);                        

        for(Task_Assignment__c selectedTask : new TaskAssignmentsSelector().selectById(taskAssignmentId))        
        {
             Time_Entry__c newEntry = new Time_Entry__c();
             newEntry.Task_Assignment__c =selectedTask.Id;
             newEntry.Date__c = Date.today();
             newEntry.Timer_Started_At__c = DateTime.Now();
             newEntry.timesheet__c = timesheetId;
             newEntry.Status__c = 'Started';
             newEntry.User__c=userId;
             uow.registerNew(newEntry); 
        }
        
        // Commit
        uow.commitWork();                                   
    }
    
     /**
	* @author Sneha
	* @date 12/1/2017
	* @description method updated TimeEntry record with the given status
 	* @param timeEntryId  id of the TimeEntry for which we are updating the status
 	* @params status status value which will be updated
	* @return none
	*/ 
    public static void updateStatus(Set<Id> timeEntryId,String status){
        SObjectUnitOfWork uow = new SObjectUnitOfWork(SERVICE_SOBJECTS);
        for(Time_Entry__c entry : new TimeEntriesSelector().selectById(timeEntryId)){
            entry.Status__c=status;
            uow.registerDirty(entry);
        }
        uow.commitWork();
    }

  
    // SObject's used by the logic in this service, listed in dependency order
    private static List<Schema.SObjectType> SERVICE_SOBJECTS = 
        new Schema.SObjectType[] { 
            Time_Entry__c.SObjectType
    };
   
}