src/objects/Time_Entry__c.object
<CustomObject>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Timer_Log__c.object
<CustomObject>
    <description>this object is used to keep track of the start &amp; stop time of the tracker</description>
    <fields>
        <fullName>Ended_At__c</fullName>
        <label>Ended At</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Started_At__c</fullName>
        <label>Started At</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Time_Entry__c</fullName>
        <label>Time Entry</label>
        <referenceTo>Time_Entry__c</referenceTo>
        <relationshipLabel>Timer Log</relationshipLabel>
        <relationshipName>Timer_Log</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Timer Log</label>
    <nameField>
        <displayFormat>TL-{0000000}</displayFormat>
        <label>Timer Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timer Log</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TimerLogsSelector.cls
public with sharing class TimerLogsSelector extends SObjectSelector {
    
     /**
	* @author Sneha
	* @date 12/1/2017
	* @description This overrides the method of base class to defined  field of this object
	* @return List of SObject field
	*/
    public override List<Schema.SObjectField> getSObjectFieldList()
    {
        return new List<Schema.SObjectField> {
            Timer_Log__c.Id,
            Timer_Log__c.Time_Entry__c,
            Timer_Log__c.Ended_At__c,
            Timer_Log__c.Started_At__c
        };
    }
    
     /**
	* @author Sneha
	* @date 12/1/2017
	* @description This overrides the method of base class to return the type of sobject
	* @return Schema.SObjectType
	*/
    public override Schema.SObjectType getSObjectType()
    {
        return Timer_Log__c.sObjectType;
    }

   /**
	* @author Sneha
	* @date 12/1/2017
	* @description this method returns all timestamp  records for a given set of timer entry records
 	* @param timeEntryId  id of the Time_Entry__c for whom records are to be fetched
	* @return list Timer_Log__c records
	*/
    public List<Timer_Log__c> selectTimerNotClosed(Set<ID> timeEntryId)
    {
        String query = String.format(
            'select {0}  from {1} ' + 
            'where Time_Entry__c in :timeEntryId AND Ended_At__c=null ' +
            'order by SystemModstamp DESC', 
            new List<String>{ getFieldListString(), getSObjectName()});
    
        return (List<Timer_Log__c>) Database.query(query);
    
    }
}